[package]
name = "sporangia"
version = "0.1.0"
edition = "2021"

# SPDX-License-Identifier: MIT

[dependencies]
bincode = "1.3.3"
bytemuck = "1.13.1"
byteorder = "1.4.3"
nom = "7.1.3"
serde = "1.0.162"
slint = "1.0.2"
