    export global Palette {
        //pure
        in-out property <color> emerald: rgba(123,217,155, 1.0);
        in-out property <color> cherise: rgba(221,51,101, 0.8);
        in-out property <color> light-brown-drab: rgba(176,134,153, 0.8);
        in-out property <color> vinaceous-tawny: rgba(199, 67, 0, 0.8);
        in-out property <color> andover-green: rgba(92, 138, 115, 0.8);
        in-out property <color> antwarp-blue: rgba(0,138, 161, 0.8);
        in-out property <color> white: rgba(255,255,255, 0.8);
        in-out property <color> black: rgba(0,0,0, 0.8);
    }